# 常用Numpy命令模板整理
[NumPy Reference](https://docs.scipy.org/doc/numpy/reference/)

In [1]:
import numpy as np

## Create a ndarray 创建矩阵

In [2]:
import numpy.random as rdm

### Pseudorandom Array 伪随机矩阵生成

In [3]:
rdm.seed(114514)  # 全局随机种子
rng = rdm.RandomState(1919180)  # 指定随机种子，生成一个numpy.random对象
arr_perm = rdm.permutation(10)  # 生成打乱矩阵
rdm.shuffle(np.arange(10))  # 打乱原矩阵
arr_randn = rdm.randn(2, 3)  # 创建一个期望为0，标准差为1的正态分布矩阵
arr_rand = rdm.rand(2, 3)  # 创建一个[0,1)均匀分布矩阵
arr_uni = rdm.uniform(2, 3, [3, 4])  # 均匀分布矩阵
arr_bin = rdm.binomial(10, 0.5, 5)  # 二项分布矩阵
arr_norm = rdm.normal(10, 10, [3, 4])  # 正态分布矩阵
arr_chis = rdm.chisquare(4, [3, 4])  # 卡方分布矩阵
arr_gamma = rdm.gamma(3, 2, [3, 4])  # 伽马分布矩阵
arr_beta = rdm.beta(3, 2, [3, 4])  # 贝塔分布矩阵
arr_randint = rdm.randint(1, 10, [2, 3])  # 创建一个指定上下界的随机整数矩阵
arr_index = rdm.choice(100, 10, replace=True)  # 创建一个范围100以内，大小为10的下标向量

In [4]:
arr_rand = np.random.rand(2, 3)  # 创建一个均匀分布的随机array

In [5]:
arr_randint = np.random.randint(1, 10, [2, 3])  # 创建一个指定上下界的随机整数矩阵

### Convert to a ndarray 转换生成

In [6]:
list1 = ['1', '2', '3', '4']
tuple1 = (5, 6, 7, 8)
arr_list = np.array([list1, tuple1],)  # list、tuple皆可作为输入参数，转化为ndarray对象

In [7]:
arr_numeric = arr_list.astype(np.int8)  # 将字符串array转换为指定类型array

In [8]:
def my_function(z, y, x):
    return x * y + z
arr_fromfunc = np.fromfunction(my_function, (3, 2, 10)) #使用自定义方程生成矩阵的方法

### Special Arries 特殊矩阵生成

In [9]:
arr_range = np.arange(10, dtype=np.int8)  # 类似range()函数创建列表
arr_linspace = np.linspace(0, 2*np.pi, 100)  # 指定起讫的均间距向量

In [10]:
arr_ones1 = np.ones([2, 3], dtype=np.float16)  # 创建全一array的两种方法
arr_ones2 = np.ones_like(arr_range)

In [11]:
arr_zeros1 = np.zeros([2, 3], dtype=np.complex64)  # 创建全零array的两种方法
arr_zeros2 = np.zeros_like(arr_range)

In [12]:
arr_empty1 = np.empty([2, 3], dtype=np.bool)  # 创建空array的两种方法
arr_empty2 = np.empty_like(arr_range)

In [13]:
arr_full1 = np.full([2, 3], 6, dtype=np.string_)  # 创建填充array的两种方法
arr_full2 = np.full_like(arr_range, 6, dtype=np.int8)

In [14]:
arr_identity = np.eye(5)  # 创建单位矩阵

### Meshgrid Array 网格矩阵

In [15]:
points_x = np.arange(-5, 5, 1)
points_y = np.arange(0, 5, 1)
xs, ys = np.meshgrid(points_x, points_y)  # 根据两个向量创建两种组合矩阵，二者同构

---
## Array Properties 矩阵参数

In [16]:
arr_rand.ndim  # 返回ndarray的维度

2

In [17]:
arr_rand.shape  # 返回(行,列)的tuple

(2, 3)

In [18]:
arr_list.dtype  # 返回数值类型

dtype('<U1')

In [19]:
arr_index = np.argwhere(arr_rand > 1)  # 查找符合条件的元素下标

## Array Alterations 矩阵操作

In [70]:
arr1 = np.random.randint(1, 10, [3, 4])
arr2 = np.random.randint(1, 10, [3, 4])
arr3 = np.ones([4, 4])
arr_ones = np.ones(4)
arr_3D = np.arange(24).reshape(4,2,3)

### Slicing and Concatenation 剪切与合并

In [59]:
arr1[:, 0:2]  # 返回前两列，但不复制矩阵
arr1_copy = arr1[0:2].copy()  # 返回前两列，产生一个独立副本
arr_vstack = np.vstack((arr1, arr2))  # 沿列合并
arr_hstack = np.hstack([arr1, arr2])  # 沿行合并
arr_concatenate = np.concatenate((arr1,arr2,arr3),axis=0) #沿指定维度合并
arr_stack = np.stack((arr1,arr2)) #将形状相同的矩阵合并成更高维度的矩阵

In [69]:
split1,split2,split3 = np.vsplit(arr1,3) #沿列等分
split1,split2 = np.hsplit(arr1,2) #沿行等分
split1,split2,split3 = np.split(arr1, 3, axis=0) #沿指定维度等分
arr1_copy = arr1[0:2].copy()  # 返回前两列，产生一个独立副本

### Reshaping 矩阵重构

In [71]:
arr1_62 = arr1.reshape(6, 2)  # 将矩阵重构为指定形状（不替换）
arr1_vec = arr1.reshape(6,-1) # 将矩阵保留第一维度，其余维度整合为一维
arr1_T = arr1.T  # 矩阵转置
arr_3D_T = arr_3D.transpose((1,2,0)) #多维矩阵转置，需要指定维度重排顺序
arr_3D_swap = arr_3D.swapaxes(0,2) #仅交换两个维度的转置
arr1.ravel() #将矩阵展开为向量

array([5, 3, 1, 3, 3, 8, 1, 5, 1, 7, 6, 6])

### Sorting 矩阵排列

In [49]:
arr1.sort(axis=1)  # 按指定维度排列，并替换原矩阵

### Iterate遍历

In [52]:
#按第一维度遍历：
for i in arr1:
    print(i)

[3 5 7 8]
[1 1 5 9]
[1 3 3 9]


In [53]:
#遍历所有元素：
for i in arr1.flat:
    print(i)

3
5
7
8
1
1
5
9
1
3
3
9


## Array Operations 矩阵计算

In [25]:
arr1 = np.random.randint(1, 10, [3, 4])
arr2 = np.random.rand(3, 4)*10
arr3 = np.random.randint(1, 10, [4, 4])
arr4 = np.arange(4)

### Unary Elementwise 单矩阵逐元素

In [26]:
arr1_abs = np.abs(arr1)  # 绝对值
arr1_sqrt = np.sqrt(np.abs(arr1))  # 开根号
arr1_square = np.square(arr1)  # 平方
arr1_time = arr1**3  # 任意次方

In [27]:
arr1_exp = np.exp(arr1)  # e为底数的幂
arr1_log = np.log(arr1)  # 自然对数
arr1_log10 = np.log10(arr1)  # 10为底的对数
arr1_log2 = np.log2(arr1)  # 2为底的对数
arr1_log1p = np.log1p(arr1)  # log(1+x)
arr1_sign = np.sign(arr1)  # sign方程

In [28]:
arr2_ceil = np.ceil(arr2)  # 向上取整
arr2_floor = np.floor(arr2)  # 向下取整
arr2_round = np.rint(arr2)  # 四舍五入
frac2, int2 = np.modf(arr2)  # 取小数、取整

In [29]:
arr1_isnan = np.isnan(arr1)  # 判断是否为数值
arr1_isfinite = np.isfinite(arr1)  # 判断是否有穷
arr1_isinf = np.isinf(arr1)  # 判断是否无穷

In [30]:
arr1_cos = np.cos(arr1)  # 各种三角函数
arr1_cosh = np.cosh(arr1)
arr1_sin = np.sin(arr1)
arr1_sinh = np.sinh(arr1)
arr1_tan = np.tan(arr1)
arr1_tanh = np.tanh(arr1)
arr2_arccos = np.arccos(arr2/10)  # 各种反三角函数
arr2_arccosh = np.arccosh(arr2/10)
arr2_arcsin = np.arcsin(arr2/10)
arr2_arcsinh = np.arcsinh(arr2/10)
arr2_arctan = np.arctan(arr2/10)
arr2_arctanh = np.arctanh(arr2/10)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in arccosh
  


### Binary Elementwise 双矩阵逐元素

In [31]:
arr_multi = arr1*arr2  # 矩阵逐项乘法1
arr_multi = np.multiply(arr1, arr2)  # 矩阵逐项乘法2
arr_devide = 1/arr1  # 矩阵逐项除法1
arr_devide = np.divide(arr1, arr2)  # 矩阵逐项除法2
arr_fdevide = np.floor_divide(arr1, arr2)  # 矩阵逐项整除
arr_mod = np.mod(arr1, arr2)  # 矩阵逐项求余
arr_add = arr1+arr2  # 矩阵逐项加法1
arr_add = np.add(arr1, arr2)  # 矩阵逐项加法2
arr_minus = arr1-arr2  # 矩阵逐项减法1
arr_subtract = np.subtract(arr1, arr2)  # 矩阵逐项减法2
arr_power = np.power(arr1, arr2)  # 矩阵1的矩阵2次方

In [32]:
arr_max = np.maximum(arr1, arr2)  # 求较大值1
arr_max = np.fmax(arr1, arr2)  # 求较大值2，忽略NaN
arr_min = np.minimum(arr1, arr2)  # 求较小值1
arr_min = np.fmin(arr1, arr2)  # 求较小值2，忽略NaN
arr_copysign = np.copysign(arr1, arr2)  # 令矩阵1同矩阵2符号相同

In [33]:
arr_greater = arr1 > arr2  # 各种布尔比大小
arr_lessequal = arr1 <= arr2
arr_equal = arr1 == 5
arr_greater = np.greater(arr1, arr2)
arr_greaterequal = np.greater_equal(arr1, arr2)
arr_less = np.less(arr1, arr2)
arr_lessequal = np.less_equal(arr1, arr2)
arr_equal = np.equal(arr1, arr2)
arr_notequal = np.not_equal(arr1, arr2)

In [34]:
arr_and = arr_less & arr_lessequal  # 各种布尔运算
arr_and = np.logical_and(arr_less, arr_lessequal)
arr_or = arr_less | arr_lessequal
arr_or = np.logical_or(arr_less, arr_lessequal)
arr_xor = arr_less ^ arr_lessequal
arr_xor = np.logical_xor(arr_less, arr_lessequal)
arr_not = ~arr_less
arr_and = np.logical_not(arr_less)

In [35]:
arr_randn = np.random.randn(4, 4)
arr_cond = np.where(arr_randn > 0, 1, -1)  # where函数，满足变量一时，填入变量二，否则填入变量三

### Matrixwise 矩阵运算

In [36]:
import numpy.linalg as lin

In [37]:
arr_dot = arr1.dot(arr3)  # 矩阵点乘1
arr_dot = np.dot(arr1, arr3)  # 矩阵点乘2
arr_dot = arr1@arr3  # 矩阵点乘3
arr_diag = np.diag(arr4)  # 向量/对角矩阵转换
arr_trace = np.trace(arr3)  # 求迹

In [38]:
arr_det = lin.det(arr3)  # 求行列式
eigen_value, eigen_vector = lin.eig(arr3)  # 求特征值和特征向量
arr_inv = lin.inv(arr3)  # 求逆
arr_pinv = lin.pinv(arr3)  # 求逆（伪）
q, r = lin.qr(arr3)  # qr分解
s, v, d = lin.svd(arr3)  # svd分解
x = lin.solve(arr3, arr4)  # 求解线性方程
a, b, c, d = lin.lstsq(arr3, arr4)  # 求解least-square方程

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


## Array Data 矩阵统计数据

In [39]:
arr1 = np.random.randint(1, 10, [3, 4])
arr2 = np.random.randint(1, 10, [3, 4])
arr3 = np.ones([4, 4])
arr_bools = (np.random.rand(3, 4)-0.5) >= 0

### Statistical Methods 统计值

In [40]:
arr1_sum = arr1.sum()  # 求和
arr1_mean = arr1.mean(axis=0)  # 求平均
arr1_std = arr1.std(axis=1)  # 求标准差
arr1_var = arr1.var()  # 求方差
arr1_min = arr1.min()  # 求最小值
arr1_mini = arr1.argmin()  # 最小值的序号
arr1_max = arr1.max()  # 求最大值
arr1_maxi = arr1.argmax()  # 最大值的序号
arr1_cumsum = arr1.cumsum()  # 累加，根据输入参数返回同构矩阵/函数
arr1_cumprod = arr1.cumprod(axis=0)  # 累乘，根据输入参数返回同构矩阵/函数

### Boolean Methods 布尔统计

In [41]:
arr_any = arr_bools.any()  # 查找是否存在true
arr_all = arr_bools.all()  # 查找是否全为true

### Array Set 集

In [42]:
arr1_unique = np.unique(arr1)  # 所有不同元素
arr_intersect = np.intersect1d(arr1, arr2)  # 求交集
arr_union = np.union1d(arr1, arr2)  # 求并集
arr_contain = np.in1d(arr1, arr2)  # 是否包含
arr_diff = np.setdiff1d(arr1, arr2)  # arr1/arr2
arr_xor = np.setxor1d(arr1, arr2)  # 并集/交集

## Save/Load SL大法

In [43]:
arr1 = np.random.randint(1, 10, [3, 4])
arr2 = np.random.rand(3, 4)*10

### Single Array S/L 保存一个矩阵

In [44]:
np.save('single_exp', arr1)  # 保存单个矩阵，格式默认为.npy
np.load('single_exp.npy')  # 读取单个矩阵

array([[8, 7, 3, 5],
       [1, 5, 1, 9],
       [3, 3, 1, 9]])

### Multiple Array S/L 保存多个矩阵

In [45]:
np.savez('multi_exp', a=arr1, b=arr2)  # 保存多个矩阵为一个字典，格式默认为.npz
arch = np.load('multi_exp.npz')  # 读取多矩阵文件
arch['b']  # 根据索引查找矩阵

array([[3.82867967, 9.01491511, 7.71566591, 7.81747535],
       [5.34561149, 9.03919636, 4.38277364, 5.36089125],
       [9.71207606, 5.70988454, 1.66724387, 4.91499857]])